update tests for squash
hpc/charliecloud pull request #1220
Opened 2021-10-29 23:42 UTC by reidpr

Addresses #693.

2021-11-05 16:51 UTC, reidpr commented
Probably would be good to run a full scope test under all three of `squash-mount`, `tar-unpack`, `squash-unpack`.

2021-11-08 19:13 UTC, j-ogas requested changes

2021-11-08 19:13 UTC, j-ogas commented on test/make-auto.d/build_custom.bats.in
> +            ch-convert "$out" "${out}.${ext}"
Shouldn't `ext=` be assigned with no leading dots? Otherwise ch-convert `"$out" "${out}.${ext}"` results in `something..sqsh`?

2021-11-10 17:05 UTC, mphinney1100 approved these changes

2021-11-10 20:49 UTC, j-ogas approved these changes

2021-11-10 20:53 UTC, merged