autotools: update make uninstall and add test
hpc/charliecloud pull request #1229
Opened 2021-11-09 20:00 UTC by j-ogas

Addresses #954.

2021-12-08 22:19 UTC, reidpr requested changes
Thanks! Couple more suggestions.

2021-12-08 22:19 UTC, reidpr commented on examples/Makefile.am
> +	rm -rf --one-file-system $(docdir)
Would `rmdir` work for these? They should be empty right? `rm -rf` is so high powered I'd like to only use it if absolutely necessary.

2021-12-08 22:19 UTC, reidpr commented on .github/workflows/main.yml
> +          $ch_prefix/from-tarball/bin/ch-run --version
What about doing this in a new step after the install isn't needed any more? Then it won't need to be reinstalled.

2021-12-17 23:27 UTC, reidpr approved these changes

2021-12-17 23:27 UTC, reidpr commented on test/Makefile.am
> +	rmdir $$(find $(pkglibexecdir) -type d | sort -r)
Nice!

2021-12-17 23:27 UTC, reidpr commented on .github/workflows/main.yml
> +      - name: ensure make uninstall works
```suggestion
      - name: make uninstall
```

2021-12-17 23:27 UTC, reidpr commented on .github/workflows/main.yml
> +          cd $ch_prefix/charliecloud-*
```suggestion
```

2021-12-20 16:31 UTC, j-ogas commented on .github/workflows/main.yml
> -          cd $ch_prefix/charliecloud-*
I had to add this to get the CI to pass; the default working directory is not /var/tmp/from-tarball`.

2022-01-20 20:55 UTC, reidpr requested changes
Please fix failing tests, then I'll merge.

2022-01-25 22:27 UTC, reidpr approved these changes

2022-01-25 22:29 UTC, merged