Rename
hpc/charliecloud pull request #1282
Opened 2022-02-19 18:29 UTC by j-ogas

Addresses #871.

2022-02-23 22:55 UTC, reidpr requested changes
Nice, several suggestions in-line.

2022-02-23 22:55 UTC, reidpr commented on bin/ch-image.py.in
> +                   help="new image name")
Removing `nargs` will make them required and then you don't need to check below.

```suggestion
   sp.add_argument("image_ref", metavar="IMAGE_REF",
                   help="old image name")
   sp.add_argument("new_ref", metavar="NEW_REF",
                   help="new image name")
```

2022-02-23 22:55 UTC, reidpr commented on doc/ch-image_desc.rst
> +   $ ch-image [...] rename IMAGE_REF NEW_REF
```suggestion
   $ ch-image [...] rename OLD_REF NEW_REF
```

2022-02-23 22:55 UTC, reidpr commented on doc/ch-image_desc.rst
> +
This should be a synopsis, not an example.

2022-02-23 22:55 UTC, reidpr commented on lib/misc.py
> +   ch.INFO("rename %s to %s" % (img.ref, new.ref))
I think this can be omitted since it just restates the command line.

2022-02-23 22:55 UTC, reidpr commented on lib/misc.py
> +      ch.FATAL("rename: %s already exists in storage" % cli.new_ref)
Maybe add `-f`, `--force` to allow overwriting?

2022-02-23 22:55 UTC, reidpr commented on lib/misc.py
> +             new.unpack_path)
There might be a `ch.rename` already that includes error checking, or possibly I dreamed it?

2022-02-23 22:55 UTC, reidpr commented on test/build/50_ch-image.bats
> +   run ch-image rename joseraulcapablanca weirdalyanvovick
```suggestion
   run ch-image rename joseraulcapablanca weirdalyanvovic
```

2022-02-23 22:55 UTC, reidpr commented on test/build/50_ch-image.bats
> +   export CH_IMAGE_STORAGE="$BATS_TMPDIR"/rename
I think rather than a new pull, you could just restore it at the end, to save downloading again.

2022-02-23 22:55 UTC, reidpr commented on test/build/50_ch-image.bats
> +   [[ $output == *"rename alpine:3.9 to alpacino"* ]]
Rather than checking output, I recommend `ch-image list` to validate.

2022-02-23 22:55 UTC, reidpr commented on test/build/50_ch-image.bats
> +   echo "$output"
Always echo the output before checking anything so errors are visible in the test output.

2022-06-17 18:37 UTC, j-ogas commented
Closing because (a) it is stale, and (b) the build-cache opens up the possibility of `tags` which warrants discussion.

2022-06-17 18:37 UTC, closed without merging