overhaul authentication flow
hpc/charliecloud pull request #1329
Opened 2022-04-13 16:24 UTC by reidpr

Closes #1318? See also PR #1324.

2022-06-07 23:16 UTC, reidpr commented
OK, here's a different proposed behavior. @adrecord, what's your take?

**Principles**

1. Charliecloud does not store credentials like Docker and Podman, and I’m disinclined to start storing any configuration, let alone secrets. If we accept this constraint, we can’t do the permanent `docker login` model. But, it’s possible to simulate it with the environment variables.

2. Usability: We want to avoid prompting for credentials if the authenticated request would also not succeed. This is impossible, because we don’t know if it would succeed until we authenticate and try it. However, how close can we come?

**Authentication models**

I saw several authentication models:

*Never*: Only try anonymous access; never try to authenticate.

*Sloppy Lazy*: Try anonymous first. If that fails, and we *suspect* authenticating might help, try to authenticate. If authentication successful, re-try the request that failed.

* This is the current behavior, but it fails on nVidia NGC (issue #1318) and possibly other registries. In principle we could improve the heuristic, but that seems hard.

*Lazy*: Try anonymous first. If that fails, and there is *any chance* authenticated might succeed, try to authenticate.

* AFAICT, this is the behavior proposed in PR #1324. I’m concerned it would yield excessive prompts for a password, e.g. if you `ch-image pull debian:bullsear` (instead of the correct `bullseye`), it will prompt for a password, try again, and still fail.

*Eager*: Try authenticating before making any requests. If this succeeds, then make all the substantive requests in authenticated mode; otherwise, make them anonymously.

* Problem: If the user just typoes the username or password, we can’t tell the difference between that and no account existing. Thus, there’s no retry of username/password within Charliecloud, and error messages might not be clear. The user would have to re-run ch-image.

*Always*: Try authenticating before making any requests. If this fails, error out. Otherwise, make all requests authenticated.

**Options**

1. Keep the current behavior (sloppy lazy). This seems bad because it doesn't work on all registries.

2. Provide comprehensive options, e.g. `--auth={never,lazy,eager,always,auto}`

3. Provide `--auth` and/or `--no-auth`. There are some sub-options:

   * `--auth` ⇒ eager vs. `--auth` ⇒ always
   * `--no-auth` ⇒ lazy vs. `--no-auth` ⇒ never
   * What is the default behavior if neither are specified?
   * Should the default change if the environment variables are specified?
   * Should we also have an environment variable e.g. `$CH_IMAGE_AUTH` to set the default?

Currently, this PR provides `--auth` to select *always* mode, a default mode of never, `--no-auth` not supported, and `$CH_IMAGE_AUTH` to set a persistent mode of *always*.

2022-06-17 14:21 UTC, j-ogas requested changes
See nitpicky suggestions.

2022-06-17 14:21 UTC, j-ogas commented on lib/charliecloud.py
> +   #                 class matches.
```suggestion
   #   scheme ...... Auth scheme string (from WWW-Authenticate header) that
   #                 this class matches.
```

2022-06-17 14:21 UTC, j-ogas commented on lib/charliecloud.py
> +         if (class_.name == auth_type):
```suggestion
      (auth_scheme, auth_d) = auth_h.split(maxsplit=1)
      auth_d = urllib.request.parse_keqv_list(
                  urllib.request.parse_http_list(auth_d))
      VERBOSE("WWW-Authenticate parsed: %s %s" % (auth_scheme, auth_d))
      # Is escalation possible in principle?
      if (len(self.escalators) == 0):
         FATAL("no further authentication possible, giving up")
      # Try to escalate.
      for class_ in self.escalators:
         if (class_.scheme == auth_scheme):
```

2022-06-17 14:21 UTC, j-ogas commented on lib/charliecloud.py
> +   name = "Basic"
```suggestion
   scheme = "Basic"
```

2022-06-17 14:21 UTC, j-ogas commented on lib/charliecloud.py
> +   name = "Bearer"
```suggestion
   scheme = "Bearer"
```

2022-06-17 14:21 UTC, j-ogas commented on lib/charliecloud.py
> +   name = "Bearer"
```suggestion
   scheme = "Bearer"
```

2022-06-17 14:21 UTC, j-ogas commented on lib/charliecloud.py
> +   name = None
```suggestion
   scheme = None
```

2022-06-17 14:21 UTC, j-ogas commented on lib/charliecloud.py
> +   #reg_auth =   # starting authentication in both modes
Do we need this comment?

2022-06-17 14:21 UTC, j-ogas commented on lib/charliecloud.py
> +               FATAL("authorization failure; don't know what to do")
```suggestion
               FATAL("authorization failure; all auth methods exhausted")
```

2022-06-17 19:05 UTC, j-ogas reviewed
Living dangerously I see, e.g., skipping CI on my suggestions?

One thing I don't see here are updates to `/test/build/40_pull.bats`, e.g., pull from previously troublesome registries like Nvidia. Do we care?

If we don't care to add a registry test and we are comfortable merging the UI suggestions without CI, then I give it my blessing.

2022-06-23 17:56 UTC, j-ogas approved these changes
LGTM.

2022-06-24 16:09 UTC, merged