update syntax to take advantage of re indexing
hpc/charliecloud pull request #1439
Opened 2022-08-30 19:38 UTC by lucaudill

2022-09-16 23:02 UTC, reidpr requested changes
Discusses offline.

2022-10-06 16:23 UTC, reidpr commented on lib/charliecloud.py
> +   def file_ensure_exists(self): # change name? e.g. ensure_exists()
I'd leave the name alone because it creates a regular file?

2022-10-06 16:25 UTC, reidpr commented on lib/charliecloud.py
> +         Path.gzip_set()
Recommend just `Path.gzip_set()` and put the conditional in that method.

2022-10-06 16:31 UTC, reidpr commented on lib/charliecloud.py
> +                    mode, *args, **kwargs) # note: removed 'self' from front of this line
What does this comment mean?

2022-10-06 16:32 UTC, reidpr commented on lib/charliecloud.py
> +      if (Path(name_new).exists()): # is this check necessary? necessary to use ossafe here?
Should figure it out and either remove the check or the comment.

2022-10-06 16:34 UTC, reidpr commented on lib/charliecloud.py
> +      "Error-checking wrapper for unlink method"
Can probably omit docstrings like this; it can be implied by the trailing underscore.

2022-10-06 16:37 UTC, reidpr commented on lib/charliecloud.py
> +      old = Storage(Path("/var/tmp/%s/ch-image" % user()))
I think you could also write this as:

```
old = Storage(Path("/var/tmp") // user // "ch-image")
```

Better? You dEcIdE 🤯🤯🤯

2022-10-06 16:52 UTC, lucaudill commented on lib/build_cache.py
> +         self.name = path.parts[-1] # name is file basename
I tried this solution in a previous iteration. I ran into issues when `path.parts` was an empty array (I believe this is the case when `path` represents `'.'`). In these cases you get an `IndexError`:
`
>>> foo = []
>>> foo[-1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
`

2022-10-06 16:56 UTC, lucaudill commented on lib/build_cache.py
> +            cwd = ch.Path(td).chdir() # check if we can move this conversion up
lol good catch. Wrote that to my future self cause I knew I'd forget

2022-10-06 17:37 UTC, lucaudill commented on bin/ch-run-oci.py.in
> +      with args.pid_file.open("wt") as fp:
Good call. Looking into it.

2022-10-06 17:59 UTC, reidpr commented on lib/build_cache.py
> +         self.name = path.parts[-1] # name is file basename
What about `path.name`?

2022-10-11 16:52 UTC, merged