update fedora build script for python 3
hpc/charliecloud pull request #1584
Opened 2023-03-06 16:03 UTC by lucaudill

2023-03-09 20:11 UTC, j-ogas requested changes
Does `shlex` come standard with python3? If not, we should probably guard against the case where it is missing. Alternatively, we may want to update autoconf to only install this script if the requisites are met.

2023-03-09 21:54 UTC, lucaudill commented
> 

`shlex` is listed on the page for the [python standard library](https://docs.python.org/3/library/). From that page:

> [T]his library reference manual describes the standard library that is distributed with Python. It also describes some of the optional components that are commonly included in Python distributions.

I'm not sure if this means that `shlex` is _always_ bundled with python, or if it's just "commonly included"...

2023-03-10 00:20 UTC, reidpr commented
I'm not aware of any stdlib modules that don't come standard, unless for the wrong OS or something like that. Regardless we do use `shlex` elsewhere already.

2023-03-10 23:16 UTC, reidpr approved these changes

2023-03-10 23:17 UTC, merged