rm non-stdlib module `packaging`
hpc/charliecloud pull request #1608
Opened 2023-03-22 16:51 UTC by reidpr

2023-03-22 19:12 UTC, reidpr commented
The cancelled check looks spurious, and internal CI passed.

2023-03-24 17:39 UTC, j-ogas requested changes
See comments.

2023-03-24 17:39 UTC, j-ogas commented on bin/ch-run-oci.py.in
> +   return tuple(re.split(r"[.-]", s)[:3])
```suggestion
def version_parse_oci(s):
   # Dead-simple version parsing for OCI; not intended for other uses.
   return tuple(re.split(r"[.-]", s)[:3])
```

2023-03-24 17:39 UTC, j-ogas commented on bin/ch-run-oci.py.in
> +   v_max = version_parse_simple(OCI_VERSION_MAX)
```suggestion
   v_min = version_parse_oci(OCI_VERSION_MIN)
   v_actual = version_parse_oci(st.config["ociVersion"])
   v_max = version_parse_oci(OCI_VERSION_MAX)
```

The method name can imply general use. The method appears to be intended for OCI version parsing only. Perhaps the method name should be a little more pointed?

2023-03-24 19:13 UTC, reidpr commented
Failed test looks spurious, and it passed internal CI.

2023-03-24 19:16 UTC, j-ogas approved these changes

2023-03-24 19:17 UTC, lucaudill approved these changes
Looks good to me

2023-03-24 19:44 UTC, merged