`ch-convert`: allow empty dirs as output
hpc/charliecloud pull request #1661
Opened 2023-05-26 20:00 UTC by lucaudill

closes #1612.

2023-05-30 21:35 UTC, lucaudill commented
@MFTabriz the feature seems to be working on my end, do you want to try it out and let me know what you think?

2023-05-30 21:55 UTC, MFTabriz commented
@lucaudill Thanks a lot for your patch. I’ll go through the changes and also test them this weekend.

2023-06-04 17:53 UTC, MFTabriz commented
@lucaudill Thanks for taking care of it. From my simple local tests, it’s working fine. 
About `unsquashfs`, I think we should open an issue for improving their documentation.

2023-06-05 15:45 UTC, lucaudill commented
@MFTabriz Awesome! Thanks for testing it out for me.

2023-06-05 17:00 UTC, reidpr requested changes
Looks nice! Couple of minor nits in-line.

2023-06-05 17:00 UTC, reidpr commented on test/run/ch-convert.bats
> +
```suggestion
```

2023-06-07 17:35 UTC, reidpr approved these changes

2023-06-07 17:36 UTC, merged