tmpfs compatibility patch for `xattr` tests
hpc/charliecloud pull request #1729
Opened 2023-09-13 19:35 UTC by lucaudill

closes #1726

2023-09-13 21:46 UTC, reidpr requested changes
Good! Suggestion for better code in-line.

2023-09-13 21:46 UTC, reidpr commented on test/build/55_cache.bats
> +    fi
You can do this more simply and idiomatically, something like:

```suggestion
    if    ! setfattr -n user.foo -v bar "$BATS_TMPDIR/tmpfs_test" \
       && [[ -z $GITHUB_ACTIONS ]]; then
        skip "xattrs unsupported in ${BATS_TMPDIR}"
    fi
```

If you did keep `run`, don't forget to `echo "$output"`.

2023-09-14 16:16 UTC, reidpr requested changes
yah you need to update the other file too lol

2023-09-14 17:02 UTC, lucaudill commented
> yah you need to update the other file too lol

oops 😬

2023-09-14 23:19 UTC, reidpr approved these changes

2023-09-14 23:20 UTC, merged