Enable gettys in Vagrantfile
hpc/charliecloud pull request #845
Opened 2020-09-11 18:48 UTC by rstyd

Addresses #840

2020-09-15 20:02 UTC, reidpr requested changes
Great that it was so short! A few suggestions:

1. Do we need five extra? I recall two, but I think actually it's just one because it was whatever was on TTY1 (which is now the autologin stuff) plus one for the test suite.
2. Document briefly why we are enabling the getty(s) here in the Vagrantfile.
3. I was pretty sure this used to be explained in the documentation somewhere? But, it needs to be documented. Even though it's a pedantic fail, we don't want to go on this chase again. Perhaps a comment at the point the test fails?

2020-09-15 20:37 UTC, rstyd commented
1. We do not. We could get away with just TTY2. I was thinking we could just enable them all since that seems to be the normal configuration Linux installations have. 
2. Will do. 
3. I'll add something to the test output.

2020-09-17 23:20 UTC, reidpr approved these changes
Looks good pending your approval of my tidy. Thanks!

2020-09-17 23:20 UTC, reidpr commented on packaging/vagrant/Vagrantfile
> +    sudo systemctl enable getty@tty2.service
This section doesn't need sudo. Could also fix the other similar errors.

2020-09-21 20:54 UTC, rstyd commented
Looks good to me!

2020-09-21 21:57 UTC, merged