keep metadata during pull and FROM
hpc/charliecloud pull request #960
Opened 2021-01-20 18:17 UTC by reidpr

Addresses: #651 and #765.
Related: #442.

2021-01-22 16:08 UTC, j-ogas approved these changes
Super excited about this. I do think the changes that preserve metadata from pull and the limitations, e.g., v2 manifest only, should be reflected in our documentation somewhere. Thoughts?

2021-01-22 18:22 UTC, reidpr commented on lib/build.py
> +         #ch.TRACE("parts remaining: %s" % dst_parts)
Yeah, it was to much blabber even for `TRACE`.

2021-01-25 22:54 UTC, reidpr commented
> I do think the changes that preserve metadata from pull and the limitations, e.g., v2 manifest only, should be reflected in our documentation somewhere.

I agree. See new commit.

2021-02-04 20:06 UTC, j-ogas requested changes

2021-02-04 20:06 UTC, j-ogas commented on lib/charliecloud.py
> +         WARNING("no metadata for image; using defaults")
Perhaps we should specify the image reference in this warning? Instead of just saying "image".

2021-02-05 20:03 UTC, merged